fix: Error: Cannot find module 'vscode-languageclient/node'
caused by a breaking change in esbuild 0.22.0 which would omit packages
from bundles targeting node (which is the case for vscode extensions) see
https://github.com/evanw/esbuild/releases/tag/v0.22.0

this commit rolls forward to esbuild 0.23.0 which reverted this
behaviour see https://github.com/evanw/esbuild/releases/tag/v0.23.0

resolves #92