docs: remove repology table
because npx vsce package doesn't like SVGs:

Error: SVGs are restricted in README.md; please use other file image formats, such as PNG: https://repology.org/badge/vertical-allrepos/typos-lsp.svg?exclude_unsupported=1